/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FHM
 */
public class dia extends javax.swing.JFrame {

    /**
     * Creates new form dia
     */
    public dia() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Dias de la semana");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jMenuItem64 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();
        jMenuItem52 = new javax.swing.JMenuItem();
        jMenuItem58 = new javax.swing.JMenuItem();
        jMenuItem51 = new javax.swing.JMenuItem();
        jMenuItem50 = new javax.swing.JMenuItem();
        jMenuItem53 = new javax.swing.JMenuItem();
        jMenuItem54 = new javax.swing.JMenuItem();
        jMenuItem55 = new javax.swing.JMenuItem();
        jMenuItem56 = new javax.swing.JMenuItem();
        jMenuItem57 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem59 = new javax.swing.JMenuItem();
        jMenuItem60 = new javax.swing.JMenuItem();
        jMenuItem61 = new javax.swing.JMenuItem();
        jMenuItem62 = new javax.swing.JMenuItem();
        jMenuItem63 = new javax.swing.JMenuItem();
        jMenuItem65 = new javax.swing.JMenuItem();
        jMenuItem66 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem67 = new javax.swing.JMenuItem();
        jMenuItem68 = new javax.swing.JMenuItem();
        jMenuItem69 = new javax.swing.JMenuItem();
        jMenuItem70 = new javax.swing.JMenuItem();
        jMenuItem71 = new javax.swing.JMenuItem();
        jMenuItem72 = new javax.swing.JMenuItem();
        jMenuItem73 = new javax.swing.JMenuItem();
        jMenuItem74 = new javax.swing.JMenuItem();
        jMenuItem75 = new javax.swing.JMenuItem();
        jMenuItem76 = new javax.swing.JMenuItem();
        jMenuItem77 = new javax.swing.JMenuItem();
        jMenuItem78 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem79 = new javax.swing.JMenuItem();
        jMenuItem80 = new javax.swing.JMenuItem();
        jMenuItem81 = new javax.swing.JMenuItem();
        jMenuItem82 = new javax.swing.JMenuItem();
        jMenuItem83 = new javax.swing.JMenuItem();
        jMenuItem84 = new javax.swing.JMenuItem();
        jMenuItem85 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem86 = new javax.swing.JMenuItem();
        jMenuItem90 = new javax.swing.JMenuItem();
        jMenuItem91 = new javax.swing.JMenuItem();
        jMenuItem92 = new javax.swing.JMenuItem();
        jMenuItem93 = new javax.swing.JMenuItem();
        jMenuItem94 = new javax.swing.JMenuItem();
        jMenuItem95 = new javax.swing.JMenuItem();
        jMenuItem96 = new javax.swing.JMenuItem();
        jMenuItem97 = new javax.swing.JMenuItem();
        jMenuItem98 = new javax.swing.JMenuItem();
        jMenuItem99 = new javax.swing.JMenuItem();
        jMenuItem100 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem87 = new javax.swing.JMenuItem();
        jMenuItem88 = new javax.swing.JMenuItem();
        jMenuItem89 = new javax.swing.JMenuItem();
        jMenuItem101 = new javax.swing.JMenuItem();
        jMenuItem102 = new javax.swing.JMenuItem();
        jMenuItem103 = new javax.swing.JMenuItem();
        jMenuItem104 = new javax.swing.JMenuItem();
        jMenuItem105 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem64.setText("jMenuItem64");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(410, 400));
        setResizable(false);

        jButton1.setText("Vista Principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("PULSE AQUI PARA VER EL LISTADO POR CADA DIA");

        jMenu2.setText("Lunes");

        jMenu7.setText("Materia");

        jMenuItem1.setText("Fundamentos de Ingenieria");
        jMenu7.add(jMenuItem1);

        jMenuItem2.setText("Seminario de Ingenieria");
        jMenu7.add(jMenuItem2);

        jMenuItem3.setText("Programacion I");
        jMenu7.add(jMenuItem3);

        jMenuItem4.setText("Programacion II");
        jMenu7.add(jMenuItem4);

        jMenuItem10.setText("Computacion Grafica");
        jMenu7.add(jMenuItem10);

        jMenuItem5.setText("Sistemas Operativos");
        jMenu7.add(jMenuItem5);

        jMenuItem6.setText("Teoria de Control");
        jMenu7.add(jMenuItem6);

        jMenuItem7.setText("Base de Datos II");
        jMenu7.add(jMenuItem7);

        jMenuItem8.setText("Inteligencia Artificial");
        jMenu7.add(jMenuItem8);

        jMenuItem9.setText("Modelacion");
        jMenu7.add(jMenuItem9);

        jMenu2.add(jMenu7);

        jMenu8.setText("Profesor");

        jMenuItem11.setText("Carlos Vargas");
        jMenu8.add(jMenuItem11);

        jMenuItem12.setText("Jorge Reyes");
        jMenu8.add(jMenuItem12);

        jMenuItem13.setText("Wilson Gordillo");
        jMenu8.add(jMenuItem13);

        jMenuItem14.setText("Fernando Sotello");
        jMenu8.add(jMenuItem14);

        jMenuItem15.setText("Esau Paloma");
        jMenu8.add(jMenuItem15);

        jMenuItem16.setText("Esperanza Merchan");
        jMenu8.add(jMenuItem16);

        jMenuItem17.setText("Oscar Bachiller");
        jMenu8.add(jMenuItem17);

        jMenuItem18.setText("Duban Ordoñez");
        jMenu8.add(jMenuItem18);

        jMenu2.add(jMenu8);

        jMenu1.add(jMenu2);

        jMenu3.setText("Martes");

        jMenu9.setText("Materia");

        jMenuItem19.setText("logica y Algoritmia");
        jMenu9.add(jMenuItem19);

        jMenuItem20.setText("Fundamentos de Programacion");
        jMenu9.add(jMenuItem20);

        jMenuItem21.setText("Elementos de Computadores");
        jMenu9.add(jMenuItem21);

        jMenuItem22.setText("Programacion I");
        jMenu9.add(jMenuItem22);

        jMenuItem23.setText("Programacion II");
        jMenu9.add(jMenuItem23);

        jMenuItem24.setText("Sistemas de Informacion ");
        jMenu9.add(jMenuItem24);

        jMenuItem25.setText("Computacion Grafica");
        jMenu9.add(jMenuItem25);

        jMenuItem26.setText("Comunicacion de Datos I");
        jMenu9.add(jMenuItem26);

        jMenuItem27.setText("Bases de Datos II");
        jMenu9.add(jMenuItem27);

        jMenuItem28.setText("Optimizacion II");
        jMenu9.add(jMenuItem28);

        jMenuItem29.setText("Electiva Basica de Ingenieria II");
        jMenu9.add(jMenuItem29);

        jMenuItem30.setText("Auditoria de Sistemas");
        jMenu9.add(jMenuItem30);

        jMenuItem31.setText("Gestion Tecnologica");
        jMenu9.add(jMenuItem31);

        jMenu3.add(jMenu9);

        jMenu10.setText("Profesor");

        jMenuItem32.setText("Eva Patricia Vasquez");
        jMenu10.add(jMenuItem32);

        jMenuItem33.setText("Pedro Melendez");
        jMenu10.add(jMenuItem33);

        jMenuItem34.setText("Jose Miguel Ojeda");
        jMenu10.add(jMenuItem34);

        jMenuItem35.setText("Joaquin Ariza");
        jMenu10.add(jMenuItem35);

        jMenuItem36.setText("Fernando Sotello");
        jMenu10.add(jMenuItem36);

        jMenuItem37.setText("Esau Paloma");
        jMenu10.add(jMenuItem37);

        jMenuItem38.setText("Carlos Vargas");
        jMenu10.add(jMenuItem38);

        jMenuItem39.setText("Esperanza Merchan");
        jMenu10.add(jMenuItem39);

        jMenuItem40.setText("Duban Ordoñez");
        jMenu10.add(jMenuItem40);

        jMenuItem41.setText("Pedro Melendez");
        jMenu10.add(jMenuItem41);

        jMenu3.add(jMenu10);

        jMenu1.add(jMenu3);

        jMenu4.setText("Miercoles");

        jMenu11.setText("Materia");

        jMenuItem42.setText("Fundamentos de Logica");
        jMenu11.add(jMenuItem42);

        jMenuItem43.setText("Programacion I");
        jMenu11.add(jMenuItem43);

        jMenuItem46.setText("Estructuras de Informacion");
        jMenu11.add(jMenuItem46);

        jMenuItem47.setText("Programacion II");
        jMenu11.add(jMenuItem47);

        jMenuItem48.setText("Computacion Grafica");
        jMenu11.add(jMenuItem48);

        jMenuItem49.setText("Bases de Datos I");
        jMenu11.add(jMenuItem49);

        jMenuItem52.setText("Teoria de Control");
        jMenu11.add(jMenuItem52);

        jMenuItem58.setText("Ingenieria de Software I");
        jMenu11.add(jMenuItem58);

        jMenuItem51.setText("Optimizacion I");
        jMenu11.add(jMenuItem51);

        jMenuItem50.setText("Ingenieria del Software II");
        jMenu11.add(jMenuItem50);

        jMenuItem53.setText("Comunicacion de Datos II");
        jMenu11.add(jMenuItem53);

        jMenuItem54.setText("Inteligencia Artificial");
        jMenu11.add(jMenuItem54);

        jMenuItem55.setText("Optimizacion II");
        jMenu11.add(jMenuItem55);

        jMenuItem56.setText("Modelacion");
        jMenu11.add(jMenuItem56);

        jMenuItem57.setText("Etica para Ingenieros");
        jMenu11.add(jMenuItem57);

        jMenu4.add(jMenu11);

        jMenu12.setText("Profesor");

        jMenuItem44.setText("Pedro Melendez");
        jMenu12.add(jMenuItem44);

        jMenuItem45.setText("Wilson Gordillo ");
        jMenu12.add(jMenuItem45);

        jMenuItem59.setText("Fernando Sotello");
        jMenu12.add(jMenuItem59);

        jMenuItem60.setText("Esau Paloma");
        jMenu12.add(jMenuItem60);

        jMenuItem61.setText("Jose Miguel Ojeda");
        jMenu12.add(jMenuItem61);

        jMenuItem62.setText("Duban Ordoñez");
        jMenu12.add(jMenuItem62);

        jMenuItem63.setText("Esperanza Merchan");
        jMenu12.add(jMenuItem63);

        jMenuItem65.setText("Oscar Bachiller");
        jMenu12.add(jMenuItem65);

        jMenuItem66.setText("Eva Patricia Vazquez");
        jMenu12.add(jMenuItem66);

        jMenu4.add(jMenu12);

        jMenu1.add(jMenu4);

        jMenu5.setText("Jueves");

        jMenu13.setText("Materia");

        jMenuItem67.setText("Fundamentos de Programacion");
        jMenu13.add(jMenuItem67);

        jMenuItem68.setText("Estructura de Informacion");
        jMenu13.add(jMenuItem68);

        jMenuItem69.setText("Microprocesadores");
        jMenu13.add(jMenuItem69);

        jMenuItem70.setText("Programacion II");
        jMenu13.add(jMenuItem70);

        jMenuItem71.setText("Sistema de Informacion");
        jMenu13.add(jMenuItem71);

        jMenuItem72.setText("Sistemas Operativos");
        jMenu13.add(jMenuItem72);

        jMenuItem73.setText("Comunicacion de Datos I");
        jMenu13.add(jMenuItem73);

        jMenuItem74.setText("Ingenieria del Software I");
        jMenuItem74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem74ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem74);

        jMenuItem75.setText("Optimizacion I");
        jMenu13.add(jMenuItem75);

        jMenuItem76.setText("Comunicacion de Datos II");
        jMenu13.add(jMenuItem76);

        jMenuItem77.setText("Ingenieria del Software II");
        jMenuItem77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem77ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem77);

        jMenuItem78.setText("Bases de Datos II");
        jMenu13.add(jMenuItem78);

        jMenu5.add(jMenu13);

        jMenu14.setText("Profesor");

        jMenuItem79.setText("Jose Miguel Ojeda");
        jMenu14.add(jMenuItem79);

        jMenuItem80.setText("Fernando Sotello");
        jMenu14.add(jMenuItem80);

        jMenuItem81.setText("Joaquin Ariza");
        jMenu14.add(jMenuItem81);

        jMenuItem82.setText("Wilson Gordillo");
        jMenu14.add(jMenuItem82);

        jMenuItem83.setText("Carlos Vargas");
        jMenu14.add(jMenuItem83);

        jMenuItem84.setText("DubanOrdoñez");
        jMenu14.add(jMenuItem84);

        jMenuItem85.setText("Esperanza Merchan");
        jMenu14.add(jMenuItem85);

        jMenu5.add(jMenu14);

        jMenu1.add(jMenu5);

        jMenu6.setText("Viernes");

        jMenu15.setText("Materia");

        jMenuItem86.setText("Logica y Algoritmia");
        jMenu15.add(jMenuItem86);

        jMenuItem90.setText("Fundamentos de Logica");
        jMenu15.add(jMenuItem90);

        jMenuItem91.setText("Microprocesadores");
        jMenu15.add(jMenuItem91);

        jMenuItem92.setText("Teoria General de Sistemas");
        jMenu15.add(jMenuItem92);

        jMenuItem93.setText("Programacion II");
        jMenu15.add(jMenuItem93);

        jMenuItem94.setText("Computacion Grafica");
        jMenu15.add(jMenuItem94);

        jMenuItem95.setText("Bases de Datos I");
        jMenu15.add(jMenuItem95);

        jMenuItem96.setText("Teoria de Control");
        jMenu15.add(jMenuItem96);

        jMenuItem97.setText("Electiva Basica de Ingenieria I");
        jMenu15.add(jMenuItem97);

        jMenuItem98.setText("Bases de Datos II");
        jMenu15.add(jMenuItem98);

        jMenuItem99.setText("Gerencia Informatica");
        jMenu15.add(jMenuItem99);

        jMenuItem100.setText("Legislacion de Ingenieria");
        jMenu15.add(jMenuItem100);

        jMenu6.add(jMenu15);

        jMenu16.setText("Profesor");

        jMenuItem87.setText("Eva Patricia Vasquez");
        jMenu16.add(jMenuItem87);

        jMenuItem88.setText("Pedro Melendez");
        jMenu16.add(jMenuItem88);

        jMenuItem89.setText("Joaquin Ariza");
        jMenuItem89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem89ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem89);

        jMenuItem101.setText("Fernando Sotello");
        jMenuItem101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem101ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem101);

        jMenuItem102.setText("Esau Paloma");
        jMenu16.add(jMenuItem102);

        jMenuItem103.setText("Carlos Vargas ");
        jMenu16.add(jMenuItem103);

        jMenuItem104.setText("Esperanza Merchan");
        jMenuItem104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem104ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem104);

        jMenuItem105.setText("Jorge Reyes");
        jMenu16.add(jMenuItem105);

        jMenu6.add(jMenu16);

        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        horarios obj=new horarios();
obj.setVisible(true);
dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem74ActionPerformed

    private void jMenuItem77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem77ActionPerformed

    private void jMenuItem89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem89ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem89ActionPerformed

    private void jMenuItem101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem101ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem101ActionPerformed

    private void jMenuItem104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem104ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem104ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dia().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem100;
    private javax.swing.JMenuItem jMenuItem101;
    private javax.swing.JMenuItem jMenuItem102;
    private javax.swing.JMenuItem jMenuItem103;
    private javax.swing.JMenuItem jMenuItem104;
    private javax.swing.JMenuItem jMenuItem105;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem52;
    private javax.swing.JMenuItem jMenuItem53;
    private javax.swing.JMenuItem jMenuItem54;
    private javax.swing.JMenuItem jMenuItem55;
    private javax.swing.JMenuItem jMenuItem56;
    private javax.swing.JMenuItem jMenuItem57;
    private javax.swing.JMenuItem jMenuItem58;
    private javax.swing.JMenuItem jMenuItem59;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem60;
    private javax.swing.JMenuItem jMenuItem61;
    private javax.swing.JMenuItem jMenuItem62;
    private javax.swing.JMenuItem jMenuItem63;
    private javax.swing.JMenuItem jMenuItem64;
    private javax.swing.JMenuItem jMenuItem65;
    private javax.swing.JMenuItem jMenuItem66;
    private javax.swing.JMenuItem jMenuItem67;
    private javax.swing.JMenuItem jMenuItem68;
    private javax.swing.JMenuItem jMenuItem69;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem70;
    private javax.swing.JMenuItem jMenuItem71;
    private javax.swing.JMenuItem jMenuItem72;
    private javax.swing.JMenuItem jMenuItem73;
    private javax.swing.JMenuItem jMenuItem74;
    private javax.swing.JMenuItem jMenuItem75;
    private javax.swing.JMenuItem jMenuItem76;
    private javax.swing.JMenuItem jMenuItem77;
    private javax.swing.JMenuItem jMenuItem78;
    private javax.swing.JMenuItem jMenuItem79;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem80;
    private javax.swing.JMenuItem jMenuItem81;
    private javax.swing.JMenuItem jMenuItem82;
    private javax.swing.JMenuItem jMenuItem83;
    private javax.swing.JMenuItem jMenuItem84;
    private javax.swing.JMenuItem jMenuItem85;
    private javax.swing.JMenuItem jMenuItem86;
    private javax.swing.JMenuItem jMenuItem87;
    private javax.swing.JMenuItem jMenuItem88;
    private javax.swing.JMenuItem jMenuItem89;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem90;
    private javax.swing.JMenuItem jMenuItem91;
    private javax.swing.JMenuItem jMenuItem92;
    private javax.swing.JMenuItem jMenuItem93;
    private javax.swing.JMenuItem jMenuItem94;
    private javax.swing.JMenuItem jMenuItem95;
    private javax.swing.JMenuItem jMenuItem96;
    private javax.swing.JMenuItem jMenuItem97;
    private javax.swing.JMenuItem jMenuItem98;
    private javax.swing.JMenuItem jMenuItem99;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
