/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FHM
 */
public class semestre extends javax.swing.JFrame {

    /**
     * Creates new form semestre
     */
    public semestre() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Semestres de la carrera");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu20 = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenu22 = new javax.swing.JMenu();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu24 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenu26 = new javax.swing.JMenu();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu27 = new javax.swing.JMenu();
        jMenuItem47 = new javax.swing.JMenuItem();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();
        jMenu28 = new javax.swing.JMenu();
        jMenuItem50 = new javax.swing.JMenuItem();
        jMenuItem51 = new javax.swing.JMenuItem();
        jMenuItem52 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenu29 = new javax.swing.JMenu();
        jMenuItem53 = new javax.swing.JMenuItem();
        jMenuItem54 = new javax.swing.JMenuItem();
        jMenuItem55 = new javax.swing.JMenuItem();
        jMenu30 = new javax.swing.JMenu();
        jMenuItem56 = new javax.swing.JMenuItem();
        jMenuItem57 = new javax.swing.JMenuItem();
        jMenuItem58 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenu31 = new javax.swing.JMenu();
        jMenuItem59 = new javax.swing.JMenuItem();
        jMenuItem60 = new javax.swing.JMenuItem();
        jMenuItem61 = new javax.swing.JMenuItem();
        jMenu32 = new javax.swing.JMenu();
        jMenuItem62 = new javax.swing.JMenuItem();
        jMenuItem63 = new javax.swing.JMenuItem();
        jMenuItem64 = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton1.setText("Vista Principal");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("PULSE AQUI PARA VER EL LISTADO DE SEMESTRES");

        jMenu3.setText("Semestre I");

        jMenu13.setText("Materia");

        jMenuItem11.setText("Fundamentos de Ingenieria");
        jMenu13.add(jMenuItem11);

        jMenuItem13.setText("Fundamentos de Logica");
        jMenu13.add(jMenuItem13);

        jMenuItem12.setText("Logica y Algoritmia");
        jMenu13.add(jMenuItem12);

        jMenu3.add(jMenu13);

        jMenu14.setText("Profesor");

        jMenuItem14.setText("Eva Patricia Vasquez");
        jMenu14.add(jMenuItem14);

        jMenuItem15.setText("Carlos Vargas");
        jMenu14.add(jMenuItem15);

        jMenuItem16.setText("Pedro Melendez");
        jMenu14.add(jMenuItem16);

        jMenu3.add(jMenu14);

        jMenu1.add(jMenu3);

        jMenu4.setText("Semestre II");

        jMenu15.setText("Materia");

        jMenuItem17.setText("Seminario de Ingenieria");
        jMenu15.add(jMenuItem17);

        jMenuItem18.setText("Fundamentos de Programacion");
        jMenu15.add(jMenuItem18);

        jMenu4.add(jMenu15);

        jMenu16.setText("Profesor");

        jMenuItem19.setText("Jorge Reyes");
        jMenu16.add(jMenuItem19);

        jMenuItem20.setText("Jorge Miguel Ojeda");
        jMenu16.add(jMenuItem20);

        jMenu4.add(jMenu16);

        jMenu1.add(jMenu4);

        jMenu5.setText("Semestre III");

        jMenu17.setText("Materia");

        jMenuItem21.setText("Programacion I");
        jMenu17.add(jMenuItem21);

        jMenuItem22.setText("Elementos de Computadores");
        jMenu17.add(jMenuItem22);

        jMenuItem23.setText("Estructuras de Informacion");
        jMenu17.add(jMenuItem23);

        jMenu5.add(jMenu17);

        jMenu18.setText("Profesor");

        jMenuItem24.setText("Wilson Gordillo");
        jMenu18.add(jMenuItem24);

        jMenuItem25.setText("Joaquin Ariza");
        jMenu18.add(jMenuItem25);

        jMenuItem26.setText("Fernando Sotello");
        jMenu18.add(jMenuItem26);

        jMenu5.add(jMenu18);

        jMenu1.add(jMenu5);

        jMenu6.setText("Semestre IV");

        jMenu19.setText("Materia");

        jMenuItem27.setText("Programacion II");
        jMenu19.add(jMenuItem27);

        jMenuItem28.setText("Teoria General de Sistemas");
        jMenu19.add(jMenuItem28);

        jMenuItem29.setText("Microprocesadores");
        jMenu19.add(jMenuItem29);

        jMenu6.add(jMenu19);

        jMenu20.setText("Profesor");

        jMenuItem30.setText("Fernando Sotello");
        jMenu20.add(jMenuItem30);

        jMenuItem31.setText("Joaquin Ariza");
        jMenu20.add(jMenuItem31);

        jMenuItem32.setText("Eva Patricia Vaesquez");
        jMenu20.add(jMenuItem32);

        jMenu6.add(jMenu20);

        jMenu1.add(jMenu6);

        jMenu7.setText("Semestre V");

        jMenu21.setText("Materia");

        jMenuItem33.setText("Computacion Grafica");
        jMenu21.add(jMenuItem33);

        jMenuItem34.setText("Sistemas Operativos");
        jMenu21.add(jMenuItem34);

        jMenuItem35.setText("Sistemas de Informacion");
        jMenu21.add(jMenuItem35);

        jMenu7.add(jMenu21);

        jMenu22.setText("Profesor");

        jMenuItem36.setText("Esau Paloma");
        jMenu22.add(jMenuItem36);

        jMenuItem37.setText("Wilson Gordillo");
        jMenu22.add(jMenuItem37);

        jMenuItem38.setText("Jose Miguel Ojeda");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu22.add(jMenuItem38);

        jMenu7.add(jMenu22);

        jMenu1.add(jMenu7);

        jMenu8.setText("Semestre VI");

        jMenu23.setText("Materia");

        jMenuItem1.setText("Teoria de Control");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu23.add(jMenuItem1);

        jMenuItem2.setText("Bases de Datos I");
        jMenu23.add(jMenuItem2);

        jMenuItem3.setText("Comunicacion de Datos I");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu23.add(jMenuItem3);

        jMenuItem4.setText("Ingenieria del Software");
        jMenu23.add(jMenuItem4);

        jMenu8.add(jMenu23);

        jMenu24.setText("Profesor");

        jMenuItem5.setText("Esau Paloma");
        jMenu24.add(jMenuItem5);

        jMenuItem6.setText("Fernando Sotello");
        jMenu24.add(jMenuItem6);

        jMenuItem7.setText("Jose Miguel Ojeda");
        jMenu24.add(jMenuItem7);

        jMenuItem8.setText("Carlos Vargas");
        jMenu24.add(jMenuItem8);

        jMenu8.add(jMenu24);

        jMenu1.add(jMenu8);

        jMenu9.setText("Semestre VII");

        jMenu25.setText("Materia");

        jMenuItem9.setText("Baes de Datos II");
        jMenu25.add(jMenuItem9);

        jMenuItem10.setText("Optimizacion I");
        jMenu25.add(jMenuItem10);

        jMenuItem39.setText("Ingenieria del Software II");
        jMenu25.add(jMenuItem39);

        jMenuItem40.setText("Comunicacion de Datos II");
        jMenu25.add(jMenuItem40);

        jMenuItem41.setText("Electiva Basica de Ingenieria I");
        jMenu25.add(jMenuItem41);

        jMenu9.add(jMenu25);

        jMenu26.setText("Profesor");

        jMenuItem42.setText("Esperanza Merchan");
        jMenu26.add(jMenuItem42);

        jMenuItem43.setText("Duvan Ordoñez");
        jMenu26.add(jMenuItem43);

        jMenuItem44.setText("Jose Miguel Ojeda");
        jMenu26.add(jMenuItem44);

        jMenuItem45.setText("Wilson Gordillo");
        jMenu26.add(jMenuItem45);

        jMenuItem46.setText("Carlos Vargas");
        jMenu26.add(jMenuItem46);

        jMenu9.add(jMenu26);

        jMenu1.add(jMenu9);

        jMenu10.setText("Semestre VIII");

        jMenu27.setText("Materia");

        jMenuItem47.setText("Optimizacion II");
        jMenu27.add(jMenuItem47);

        jMenuItem48.setText("Inteligencia Artificial");
        jMenu27.add(jMenuItem48);

        jMenuItem49.setText("Electiva Basica de Ingenieria II");
        jMenu27.add(jMenuItem49);

        jMenu10.add(jMenu27);

        jMenu28.setText("Profesor");

        jMenuItem50.setText("Oscar Bachiller");
        jMenu28.add(jMenuItem50);

        jMenuItem51.setText("Duban Ordoñez");
        jMenu28.add(jMenuItem51);

        jMenuItem52.setText("Pedro Melendez");
        jMenu28.add(jMenuItem52);

        jMenu10.add(jMenu28);

        jMenu1.add(jMenu10);

        jMenu11.setText("Semestre IX");

        jMenu29.setText("Materia");

        jMenuItem53.setText("Modelacion");
        jMenu29.add(jMenuItem53);

        jMenuItem54.setText("Auditoria de Sistemas");
        jMenu29.add(jMenuItem54);

        jMenuItem55.setText("Gerencia Informatica");
        jMenu29.add(jMenuItem55);

        jMenu11.add(jMenu29);

        jMenu30.setText("Profesor");

        jMenuItem56.setText("Duban Ordoñez");
        jMenu30.add(jMenuItem56);

        jMenuItem57.setText("Joaquin Ariza");
        jMenu30.add(jMenuItem57);

        jMenuItem58.setText("Carlos Vargas");
        jMenu30.add(jMenuItem58);

        jMenu11.add(jMenu30);

        jMenu1.add(jMenu11);

        jMenu12.setText("Semestre X");

        jMenu31.setText("Materia");

        jMenuItem59.setText("Gestion Tecnologica");
        jMenu31.add(jMenuItem59);

        jMenuItem60.setText("Etica para Ingenieros");
        jMenu31.add(jMenuItem60);

        jMenuItem61.setText("Legislacion de Ingenieria");
        jMenuItem61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem61ActionPerformed(evt);
            }
        });
        jMenu31.add(jMenuItem61);

        jMenu12.add(jMenu31);

        jMenu32.setText("Profesor");

        jMenuItem62.setText("Jose Miguel Ojeda");
        jMenu32.add(jMenuItem62);

        jMenuItem63.setText("Eva Patricia Vasquez");
        jMenu32.add(jMenuItem63);

        jMenuItem64.setText("Jorge Reyes");
        jMenu32.add(jMenuItem64);

        jMenu12.add(jMenu32);

        jMenu1.add(jMenu12);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
      horarios obj=new horarios();
      obj.setVisible(true);
      dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem61ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(semestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(semestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(semestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(semestre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new semestre().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem52;
    private javax.swing.JMenuItem jMenuItem53;
    private javax.swing.JMenuItem jMenuItem54;
    private javax.swing.JMenuItem jMenuItem55;
    private javax.swing.JMenuItem jMenuItem56;
    private javax.swing.JMenuItem jMenuItem57;
    private javax.swing.JMenuItem jMenuItem58;
    private javax.swing.JMenuItem jMenuItem59;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem60;
    private javax.swing.JMenuItem jMenuItem61;
    private javax.swing.JMenuItem jMenuItem62;
    private javax.swing.JMenuItem jMenuItem63;
    private javax.swing.JMenuItem jMenuItem64;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
